name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      # 分支
      target_branch:
        description: select the target branch to publish
        required: true
        default: main
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # id-token 的权限是必须的
      packages: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: pnpm

      - run: pnpm install
      - run: pnpm build

      # 压缩 dist 文件夹
      - name: zip dist folder
        run: |
          zip -r -q dist.zip dist/
          ls -lh dist.zip

      # 打tag并推送
      - name: create and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          GIT_API_TAGGING: false
          INITIAL_VERSION: 1.0.0

      - name: Generate Changelog
        id: generate_changelog
        uses: lxqmoma/simple-changelog-action@v1
        with:
          new_tag: ${{ steps.tag_version.outputs.new_tag }}
          old_tag: ${{ steps.tag_version.outputs.old_tag }}

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          files: dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release
